name: ".NET"
on:
  push:
    branches:
      - "main"
  pull_request:
    branches:
      - "main"

jobs:
  build:
    runs-on: "ubuntu-24.04"
    steps:
      - uses: actions/checkout@v5
      - name: Setup .NET
        uses: actions/setup-dotnet@v4
        with:
          dotnet-version: '8.0.x'
          dotnet-quality: 'preview'
      - name: Install dependencies
        working-directory: 'csharp/VaultExample'
        run: dotnet restore
      - name: Build
        working-directory: 'csharp/VaultExample'
        run: dotnet build --configuration Release --no-restore
